async function generateSummary({ title = "", text = "" } = {}) {
  const content = String(text || "").trim();

  const fallbackPoints = [
    `This content is focused on learning around "${title || "the selected topic"}".`,
    "Important concepts can be converted into notes and bookmarks for revision.",
    "A short quiz after watching helps improve retention and understanding."
  ];

  if (!content) {
    return {
      provider: "stub",
      summary: fallbackPoints.join(" "),
      keyPoints: fallbackPoints
    };
  }

  const snippet = content.slice(0, 800);

  return {
    provider: "stub",
    summary: `Summary for "${title || "Untitled"}": ${snippet}`,
    keyPoints: [
      "Core concepts were identified from the available content.",
      "The topic can be revised using notes, bookmarks, and quizzes.",
      "This summary is currently generated by the internal fallback provider."
    ]
  };
}

async function answerDoubt({ question = "", context = "" } = {}) {
  return {
    provider: "stub",
    answer: `Question received: "${question}". A connected AI provider is not configured yet, so this is a fallback response based on available context.`,
    contextPreview: String(context || "").slice(0, 400)
  };
}

module.exports = {
  generateSummary,
  answerDoubt
};